### ISSUE TITLE
Encoder glitched and crashed the program

### ISSUE THREAD

**Issue by AjTech1089** [t1stm/ThirtyDollarWebsiteConverter#13]
Ok so when I was using the beta program, I tried using my sequence that had the 12 new sounds that The Thirty Dollar Website had, and the encoder couldn't read it and it immediately glitched and crashed the program. I think the code for searching up new sounds automatically didn't work so I think it should be manually searched by hand.

**Comment by AjTech1089** [comment]
By the way, you can check my sequence and load it into the thirty-dollar website.
[AjTech1089s Sequence (Please load this in the thirty-dollar website to check why it cannot be converted).zip](https://github.com/t1stm/ThirtyDollarWebsiteConverter/files/12384677/AjTech1089s.Sequence.Please.load.this.in.the.thiry.dollar.website.to.check.why.it.cannot.be.converted.zip)
 to see why it isn't working with the program.

**Comment by t1stm** [comment]
The issue was very simple, and a dumb overlook on my end (+ some missed testing).
To explain it frankly, the last event in your sequence "!loopmany@2" was coded to look for "!looptarget", but since your sequence doesn't have it, the program doesn't find it and goes out of bounds. 

Since this is a reverse-engineering project, I don't have access to the original code. This is one of the things I like about open source development. As a person you can't think of all the edge cases.

Anyways I've attached a screenshot of the fixed code, and will submit a bug-fix release soon. The line causing the program to go _boom_ is highlighted with the red arrow.
![image](https://github.com/t1stm/ThirtyDollarWebsiteConverter/assets/88944096/553a50fb-56b3-4ab2-8722-91369981775e)

**Comment by t1stm** [comment]
I'll close this issue when I release the bug-fix.

**Comment by t1stm** [comment]
Please wait a bit before trying the latest bug-fix. Your sequence helped me find another bug with encoding.

**Comment by t1stm** [comment]
The application is safe to download now. [Download Link](https://github.com/t1stm/ThirtyDollarWebsiteConverter/tags)
